Repository GatorEducator/IRBeast, pull requests merged in 2019-04, with the labels that each got.

#14 Add gitignore
  .gitignore
Labels: enhancement

#15 Add CONTRIBUTING.md & CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, enhancement, priority

#21 Add the basic status badges
  README.md
Labels: documentation

#20 Implementing codecov.yml
  .travis.yml
  codecov.yml
Labels: enhancement, help wanted, testing
